---
title: "index"
output: html_document
---

```{r load libraries}

library(tidyverse)
library(readxl)

options(digits=2)
options(scipen = 999)

```

# County by County Canvass Report

Texas Secretary of State publishes county by county election results at [results.texas-election.com](https://results.texas-election.com/races).


```{r load Texas Election Results 2024}

df <- read_excel("data/CountybyCountyCanvassReport.xlsx")

prez2024 <- df %>%
  select(-`ELECTION DATE-NAME`) %>%
  filter(`OFFICE NAME` == "PRESIDENT/VICE-PRESIDENT")

```


```{r president results tidying}

# rename spaced variable names
lookup <- c(OFFICE = "OFFICE NAME",
            CANDIDATE = "CANDIDATE NAME",
            COUNTY = "COUNTY NAME",
            TOTAL_VOTES = "TOTAL VOTES PER OFFICE PER COUNTY")
prez2024 <- rename(prez2024, all_of(lookup)) 


# remove comma from any vote tallies
prez2024 <- prez2024 %>% 
  mutate(TOTAL_VOTES = as.numeric(gsub(",", "", TOTAL_VOTES)))

# pivot county totals wider
prez2024wider <- prez2024 %>%
  pivot_wider(
    id_cols = COUNTY,
    names_from = CANDIDATE,
    values_from = TOTAL_VOTES,
    values_fill = list(TOTAL_VOTES = 0)
    ) %>%
  mutate(TotalVOTES = rowSums(across(-COUNTY))) %>% # total by county votes
  mutate(VoteSHARE = round((TotalVOTES / sum(TotalVOTES)), 3))


```

```{r}

top15counties <- prez2024wider %>%
  arrange(desc(TotalVOTES)) %>%
  select(COUNTY, TotalVOTES, VoteSHARE) %>%
  slice_max(VoteSHARE, n = 10) %>%
  sum(VoteSHARE)

```

```{r texas gis data}

sf <- shapefile(filename = "data/gis/counties/Texas_County_Boundaries_4845315375211121464")


```



